DROP TABLE computer IF EXISTS;
DROP TABLE company IF EXISTS;

CREATE TABLE company (
  ca_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  ca_name VARCHAR(255) NOT NULL)
;

CREATE TABLE computer (
  cu_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  cu_name VARCHAR(255) NOT NULL,
  cu_introduced DATETIME NULL,
  cu_discontinued DATETIME NULL,
  cu_ca_id BIGINT DEFAULT NULL,
  CONSTRAINT fkey FOREIGN KEY (cu_ca_id) REFERENCES company (ca_id))
;



CREATE USER admincdb PASSWORD "qwerty1234" ADMIN;

GRANT ALL ON computer TO admincdb;
GRANT ALL ON company TO admincdb;




INSERT INTO company (ca_id,ca_name) VALUES (  1,'Apple Inc.');
INSERT INTO company (ca_id,ca_name) VALUES (  2,'Thinking Machines');
INSERT INTO company (ca_id,ca_name) VALUES (  3,'RCA');
INSERT INTO company (ca_id,ca_name) VALUES (  4,'Netronics');
INSERT INTO company (ca_id,ca_name) VALUES (  5,'Tandy Corporation');

INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  1,'MacBook Pro 15.4 inch',null,null,1);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  2,'CM-2a',null,null,2);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  3,'CM-200',null,null,2);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  4,'CM-5e',null,null,2);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  5,'CM-5','1991-01-01',null,2);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  6,'MacBook Pro','2006-01-10',null,1);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  7,'Apple IIe',null,null,null);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  8,'Apple IIc',null,null,null);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES (  9,'Apple IIGS',null,null,null);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES ( 10,'Apple IIc Plus',null,null,null);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES ( 11,'Apple II Plus',null,null,null);
INSERT INTO computer (cu_id,cu_name,cu_introduced,cu_discontinued,cu_ca_id) VALUES ( 12,'Apple III','1980-05-01','1984-04-01',1);
